// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3HeiLbyPbNtYR2hyeXrkYkrQgVmqbvcg',
    appId: '1:873677317681:web:344e20866872b742849710',
    messagingSenderId: '873677317681',
    projectId: 'flutter-test-6364b',
    authDomain: 'flutter-test-6364b.firebaseapp.com',
    databaseURL: 'https://flutter-test-6364b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-test-6364b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9EeyMlvoYAb9dq5r07SOQK6GiRg-U5pE',
    appId: '1:873677317681:android:d84448886f5eb18b849710',
    messagingSenderId: '873677317681',
    projectId: 'flutter-test-6364b',
    databaseURL: 'https://flutter-test-6364b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-test-6364b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt-zAgmsuLsLDITmNtkWKaKHmOwSm6GW4',
    appId: '1:873677317681:ios:bc8fc70b6b1527cf849710',
    messagingSenderId: '873677317681',
    projectId: 'flutter-test-6364b',
    databaseURL: 'https://flutter-test-6364b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-test-6364b.appspot.com',
    iosBundleId: 'com.lcdsoft.flutter.chat',
  );
}
